### ISSUE TITLE
compression not working

### ISSUE THREAD

**Issue by dportabella** [qubitstream/phpmyadmin_sql_backup#4]
thanks for sharing the script!
I successfully use it to backup my db, which results in a 1Gb sql file when using no compression.
However, `--compresion zip` results in an empty file.
And `--compression gzip` results in a file, that once gunziped, it has 626Mb, instead of 1Gb.

Any idea of what can be the problem?
I've tried both in OSX and CentOS release 6.8. Python 3.4, and phpmysql 4.6.6.

**Comment by qubitstream** [comment]
This script is rather simple and does not do any verification whether your specified export options are really available. If you specify `zip` as compression, this must be enabled (& selectable) in the phpmyadmin Web UI, otherwise it will fail.

So when you open phpmyadmin in your browser, go to "home" > "export" and select "custom options"; these options set here are all the settings this script uses, with only the "databases" and "compression" option customisable as script parameters.

As for the difference between the uncompressed and `gzip` compressed export - I just tested it on phpmyadmins demo site, and the uncompressed and gzipped sql files are the same. Hm.

Have you tried it in the Web UI?
The resulting export file via the Web UI and this script should be the same.

**Comment by dportabella** [comment]
I see, I though the zip and gzip was done at the client side.
Yes, I've tested with from the Web UI and I have the same problem, so it is not an issue of your script.
